# Generated by Django 2.1.3 on 2018-12-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181211_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_original_img', 'Can view the original image of a blog post'), ('run_seeds', 'Can sun seed methods against the database'), ('run_exports', 'Can run user and blog exports'))},
        ),
    ]
