# Generated by Django 2.1.3 on 2018-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cooking_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
