# Generated by Django 2.1.3 on 2019-01-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190106_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recepie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='blog.Post'),
        ),
    ]
